
plugins: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - db/views_schema.rb
    - config/initializers/secret_token.rb
    - script/rails
    - bin/*
    - vendor/**/*
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/development.rb'
    - 'lib/tasks/*'
Layout/LineLength:
  Max: 120
Style/Documentation:
  Exclude:
    - "spec/**/*"
Style/NumericPredicate:
  Exclude:
    - lib/deployed_version.rb
    - lib/psd_formatter.rb
RSpec/DescribeClass:
  Exclude:
    - spec/views/*
    - spec/api/v1/*
Style/ClassAndModuleChildren:
  Enabled: false
